releases/20150205234134/releases/20150205213414/releases/20150205112743/config/routes.rb
Rails.application.routes.draw do
  resources :resources, :path => '/'

  resources :resources do
    collection do
      get 'getnodes'
      get 'getlightnodes'
      get 'gettemperaturenodes'
    end
  end

end

releases/20150205234134/releases/20150205213414/releases/20150205112743/app/models/resource.rb
class Resource < ActiveRecord::Base
  validates :node_id, presence: true
  validates :hardware, presence: true
  validates :hostname, presence: true
  def lightnodes
    Resource.where(:name => 'light')
  end
  def temperaturenodes
    Resource.where(:name => 'temperatur')
  end
end

releases/20150205234134/releases/20150205213414/releases/20150205112743/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

releases/20150205234134/releases/20150205213414/releases/20150205112743/app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  respond_to :json
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all
    # respond_to do |format|
    #   format.html
    #   format.json {render json: @resources}
    # end
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: 'Resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def getnodes
    @nodes = Resource.all
    respond_with(@nodes) do |format|
      format.json { render :json => @nodes.as_json }
    end
  end

  def getlightnodes
    nodes = Resource.new
    @lightnodes = nodes.lightnodes
    respond_with(@lightnodes) do |format|
      format.json { render :json => @lightnodes.as_json }
    end
  end

  def gettemperaturenodes
    nodes = Resource.new
    @temperaturenodes = nodes.temperaturenodes
    respond_with(@temperaturenodes) do |format|
      format.json { render :json => @temperaturenodes.as_json }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:port, :protocol, :hardware, :hostname, :type, :name, :path, :ip, :node_id)
    end
end

releases/20150205234134/releases/20150205213414/releases/20150205112743/app/helpers/application_helper.rb
module ApplicationHelper
end

releases/20150205234134/releases/20150205213414/releases/20150205112743/app/helpers/resources_helper.rb
module ResourcesHelper
end

releases/20150205234134/releases/20150205213414/releases/20150205112743/app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :port %><br>
    <%= f.number_field :port %>
  </div>
  <div class="field">
    <%= f.label :protocol %><br>
    <%= f.text_field :protocol %>
  </div>
  <div class="field">
    <%= f.label :hardware %><br>
    <%= f.text_field :hardware %>
  </div>
  <div class="field">
    <%= f.label :hostname %><br>
    <%= f.text_field :hostname %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type_resource %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :node_id %><br>
    <%= f.text_field :node_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

releases/20150205234134/releases/20150205213414/releases/20150205112743/app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

releases/20150205234134/releases/20150205213414/releases/20150205112743/app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <thead>
    <tr>
      <th>Port</th>
      <th>Protocol</th>
      <th>Hardware</th>
      <th>Hostname</th>
      <th>Type</th>
      <th>Name</th>
      <th>Path</th>
      <th>Ip</th>
      <th>Node</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.port %></td>
        <td><%= resource.protocol %></td>
        <td><%= resource.hardware %></td>
        <td><%= resource.hostname %></td>
        <td><%= resource.type_resource %></td>
        <td><%= resource.name %></td>
        <td><%= resource.path %></td>
        <td><%= resource.ip %></td>
        <td><%= resource.node_id %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

releases/20150205234134/releases/20150205213414/releases/20150205112743/app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

releases/20150205234134/releases/20150205213414/releases/20150205112743/app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Port:</strong>
  <%= @resource.port %>
</p>

<p>
  <strong>Protocol:</strong>
  <%= @resource.protocol %>
</p>

<p>
  <strong>Hardware:</strong>
  <%= @resource.hardware %>
</p>

<p>
  <strong>Hostname:</strong>
  <%= @resource.hostname %>
</p>

<p>
  <strong>Type:</strong>
  <%= @resource.type_resource %>
</p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Path:</strong>
  <%= @resource.path %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @resource.ip %>
</p>

<p>
  <strong>Node:</strong>
  <%= @resource.node_id %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>